import { app, BrowserWindow } from 'electron';
import log from 'electron-log';
import { initDatabase, closeDatabase } from './main/core/database/connection';
import { runMigrations } from './main/core/database/migrationRunner';
import { registerIpcHandlers } from './main/ipc/handlers';
import { BackupService } from './main/core/services/BackupService';
import { getWhatsAppService } from './main/core/services/WhatsAppService';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Configure logging
log.transports.file.level = 'info';
log.transports.console.level = 'debug';

const createWindow = (): void => {
  const path = require('path');

  const isDev = process.env.NODE_ENV === 'development';
  // Use the webpack-provided preload path in dev *if* it's available, otherwise fall back to packaged preload
  const preloadPath = isDev && typeof MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY !== 'undefined'
    ? MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    : path.join(__dirname, 'preload.js');

  // Debugging: log which preload path will be used
  log.info('Using preload path:', preloadPath);

  // Determine correct icon path for both development and production
  const iconPath = app.isPackaged
    ? path.join(process.resourcesPath, 'assets', 'icon.ico')
    : path.join(__dirname, '..', 'assets', 'icon.ico');
  
  log.info('Using icon path:', iconPath);

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    icon: iconPath,
    title: 'AgorraLab',
    // Hide the menu bar automatically (useful for Windows builds)
    autoHideMenuBar: true,
    webPreferences: {
      preload: preloadPath,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // Ensure the menu bar is not visible
  mainWindow.setMenuBarVisibility(false);

  // Set Content Security Policy
  // Note: 'unsafe-eval' is required for sql.js WASM to work properly
  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          process.env.NODE_ENV === 'development'
            ? "default-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
            : "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self';"
        ]
      }
    });
  });

  // and load the index.html of the app.
  // In development, prefer the webpack-provided entry if available, otherwise use Vite dev server
  const devServerUrl = process.env.VITE_DEV_SERVER_URL || 'http://localhost:5173';
  const loadUrl = isDev
    ? (typeof MAIN_WINDOW_WEBPACK_ENTRY !== 'undefined' ? MAIN_WINDOW_WEBPACK_ENTRY : devServerUrl)
    : `file://${path.join(__dirname, '../dist/index.html')}`;

  log.info('Loading renderer URL:', loadUrl);
  mainWindow.loadURL(loadUrl);

  // Open the DevTools.
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
};

// Initialize database and migrations before creating window
async function initializeApp(): Promise<void> {
  try {
    log.info('Initializing application...');
    
    // Initialize database
    await initDatabase();
    log.info('Database initialized');
    
    // Run migrations
    await runMigrations();
    log.info('Migrations completed');
    
    // Register IPC handlers
    registerIpcHandlers();
    log.info('IPC handlers registered');
    
    // Initialize auto backup if enabled
    const backupService = new BackupService();
    await backupService.checkAndRunAutoBackup();
    log.info('Auto backup initialized');
    
    // Initialize WhatsApp service (will auto-restore session if exists)
    const whatsAppService = getWhatsAppService();
    await whatsAppService.initialize();
    log.info('WhatsApp service initialized');
    
    // Create window
    createWindow();
    log.info('Application initialized successfully');
  } catch (error) {
    log.error('Failed to initialize application:', error);
    app.quit();
  }
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', initializeApp);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    closeDatabase();
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Save database before quitting
app.on('before-quit', () => {
  log.info('Application quitting, closing database...');
  closeDatabase();
});